# Site settings
title: Lov za svobodo
description: > 
  Zdravo! Lov za svobodo za vsakega posameznika pomeni različne stvari.
  Moje ime je <strong>Timi Hraš</strong> in to je moje življenje, 
  moja zgodba, moje izkušnje in lov za iskanjem svobode. 
baseurl: "" 
url: "" 
permalink: /:categories/:title
excerpt_separator: <!--more-->

# Author information
author: Timi Hraš
email: hi@lovzasvobodo.si

social: 
  - title: instagram
    link:  "https://instagram.com/lovzasvobodo"
  - title: twitter
    link: "https://twitter.com/lovzasvobodo"
  - title: facebook
    link:  "https://facebook.com/lovzasvobodo"
  - title: youtube
    link:  "https://youtube.com/lovzasvobodo"

# Google Analytics
analytics: UA-98424691-1

# Disqus
disqus_shortname: "lovzasvobodo"

# Build settings
include: ["_categories","_pages"]
markdown: kramdown
plugins:
- jekyll-paginate
- jekyll-paginate-v2
- jekyll-sitemap

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
# END Build settings


# Site configuration for the Jekyll 3 Pagination 
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'
# END Pagnation