# Site settings
title: Your awesome title
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
disqus_shortname: "lovzasvobodo"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Owner/author information
owner:
  name: Your Name
  avatar: avatar.jpg
  bio: "Your bio goes here. It shouldn't be super long but a good sentence or two should suffice."
  email: you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: "https://twitter.com/lovzasvobodo"
  facebook: "https://facebook.com/lovzasvobodo"
  instagram: "https://instagram.com/lovzasvobodo"
  youtube: "https://instagram.com/lovzasvobodo"

