# Site settings
title: Lov za svobodo
author: Timi Hraš
email: hi@lovzasvobodo.si
description: > # this means to ignore newlines until "baseurl:"
  Zdravo! Lov za svobodo za vsakega posameznika pomeni različne stvari.
  Moje ime je <strong>Timi Hraš</strong> in to je moje življenje, 
  moja zgodba, moje izkušnje in lov za iskanjem svobode. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
disqus_shortname: "lovzasvobodo"
permalink: /:categories/:title
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

plugins:
- jekyll-paginate
- jekyll-paginate-v2
- jekyll-sitemap
#   - jekyll-feed

include: ["_categories","_pages"]

# Owner/author information
owner:
  name: Timi Hraš
  avatar: timi_hras.jpg
  # Social networking links used in footer. Update and remove as you like.
  social: 
    - title: instagram
      link:  "https://instagram.com/lovzasvobodo"
    - title: twitter
      link: "https://twitter.com/lovzasvobodo"
    - title: facebook
      link:  "https://facebook.com/lovzasvobodo"
    - title: youtube
      link:  "https://youtube.com/lovzasvobodo"

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  # title: ':title - page :num'
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################