# Site settings
title: Lov za svobodo
author: Timi Hraš
email: hello@lovzasvobodo.si
description: > # this means to ignore newlines until "baseurl:"
  Zdravo! Lov za svobodo za vsakega posameznika pomeni različne stvari.
  Tukaj je moja zgodba, moje življenjske izkušnje in moja avantura v lovu 
  za iskanje svobode. Ime mi je <strong>Timi</strong> in sem bloger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
disqus_shortname: "lovzasvobodo"
permalink: /:year/:month/:title
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

# Owner/author information
owner:
  name: Timi Hraš
  avatar: timi_hras.jpg
  bio: "Your bio goes here. It shouldn't be super long but a good sentence or two should suffice."
  email: timi@lovzasvobodo.si
  # Social networking links used in footer. Update and remove as you like.
  social: 
    - title: twitter
      link: "https://twitter.com/lovzasvobodo"
    - title: facebook
      link:  "https://facebook.com/lovzasvobodo"
    - title: instagram
      link:  "https://instagram.com/lovzasvobodo"
    - title: youtube
      link:  "https://youtube.com/lovzasvobodo"

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
